
language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

osx_image: xcode9

sudo: false

env:
  global:
    - secure: bJurUlhy79EDF5N/6al+J6Hq5AY9lS019hWKSp8djCFMatX6RZbfiAbyHGaVBgDTU4sVD5Hpr447pf+6p6M+0BiWEOqpvc1ALrd50xJ5Wa6pUESmTLNWa47bDjIO37cHTjH7JR8Q0/8vZ9I9vDIRUkwEn296ztF5K8e1kLFf4wLDyMa4UWB/g6LakS15AI+H+E4MSrnBlYO8GJEmfPepDdBXs49FF8cFWzR8lZYmKgO46JYeUihYUEnmWDZVRVrd7Iot0JRKSo0gUZPAyA47cWGtMXPoGAo/10TONZzfQu95xYuA53s9XJOgdvtwNVW0XfG5ZivvbrDVkoPX/tJ+5Cqpf5Fx+IFguP0lBb6xusUO6unLd1YM9wlb94/ip+bNS5fsaCmEwWBn0+vEISolYcMKmYKOMkEarll7wfyK3w5NJ0NR9I+3cCB8pNIDXAkjl+n6z8TWxUkV+VrdN37OJyOgIvi8O3EDrZUiv8T04xlU+CnqYWdRCiqjtEul4agjs0WSBpWPsOSI8gMyXqAKOGlKyu1kfcBhMzuNIrxaW33HdqNQItxAMdlfP7YW0AEzN+rYhTYG8PltaDwU3o38hBh2hmW1io+cN3miwvy4IEAi/tWkrnkKaV4FX0W82o2ym/rvwAbCQhGQ23ca0nqqs1YVrtDOMgd/gqBwzR2R3gs=
    - MAKEJOBS=-j3
    - ENABLE_COVERAGE=no
    - ENABLE_VALGRIND=no
  matrix:
    - MAKETARGET=distcheck
    - MAKETARGET=check MAKEJOBS=-j1 ENABLE_COVERAGE=yes
    - MAKETARGET=check MAKEJOBS=-j1 ENABLE_VALGRIND=yes
    - MAKETARGET=pkg-deb DEPLOY=yes
    - MAKETARGET=pkg-rpm DEPLOY=yes
    - MAKETARGET=pkg-bin DEPLOY=yes

matrix:
  exclude:
    - os: osx
      env: MAKETARGET=pkg-deb DEPLOY=yes
    - os: osx
      env: MAKETARGET=pkg-rpm DEPLOY=yes
    - compiler: clang
      env: MAKETARGET=pkg-deb DEPLOY=yes
    - compiler: clang
      env: MAKETARGET=pkg-rpm DEPLOY=yes
    - compiler: clang
      env: MAKETARGET=pkg-bin DEPLOY=yes
    - compiler: clang
      env: MAKETARGET=check MAKEJOBS=-j1 ENABLE_COVERAGE=yes

cache:
  apt: true

addons:
  apt_packages:
      - libgmp-dev
      - lcov
      - valgrind
      - libtool
      - libltdl-dev
      - dpkg-dev
      - debhelper
      - fakeroot
      - rpm
  coverity_scan:
    project:
      name: libbitc/libbitc
    notification_email: libbitc@users.noreply.github.com
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command: make check
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a06a330810e8b0a9300
    on_success: change
    on_failure: always
    on_start: never
  slack: libbitc:LzNZosd4L6ZkORMznw0mwrq7

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install argp-standalone; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_COVERAGE" = "yes" ]; then brew install lcov; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ENABLE_VALGRIND" = "yes" ]; then brew install valgrind; fi
  - if [ "$ENABLE_COVERAGE" = "yes" ]; then gem install coveralls-lcov; fi

before_script:
  - ./autogen.sh

script:
  - LIBBITC_CONFIG="--enable-coverage=$ENABLE_COVERAGE --enable-valgrind=$ENABLE_VALGRIND"
  - LIBBITC_CONFIG_ALL="--cache-file=config.cache"
  - ./configure $LIBBITC_CONFIG_ALL $LIBBITC_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $MAKETARGET || ( echo "Build failure. Verbose build follows." && make V=1 $MAKETARGET; false )

after_success:
      - if [ "$ENABLE_COVERAGE" = "yes" ]; then lcov --capture --compat-libtool --directory . --no-external --output-file coverage.info.all && lcov --remove coverage.info.all */test/* */external/* -o coverage.info && coveralls-lcov coverage.info; fi

deploy:
  provider: releases
  api_key:
    secure: BKWW9tKs+Gped75ACIWq+cO5KS0EQcutkbDxY745k8CeKZ+3D2DxEC1Mtpn8aBYVX4pv+zAui0Nt1ov0iag48AEhcqRm/hPeC1BlOVjgKL0gYsZH7pwb2cugPOrt19Eto5oey5tkFEVGDUbrBmyp2wkH/f+E/fsd3HYh7DE+Ogopron4Qhx/cyHz+Sl12pTwQtqqIY4FiFNeW8iumYS4fA0GoPoeZ+Wt2HC9jgD3C+2lTnyTfUrJQ3qXwc4qWjuoxVcEp6zKwLgNwMs2TPkdCKc2rbERlbUniY/+L+IUj4JP63AkMrSEhhYubqq9sbFFyYA2NoufCdCQCPktxPvstQyt8vCUzZExFJIZphHfQGfmeN5VxwMeJiDrrcxyhlJfQ75rcc+ccn/e9B11MQlBAwn7+lcf/K8vf6uRUvWTH5DNruoOjb3z9CJoZaG+JgNoS+h93XoarMXFXOJYvysQQRk1k8daNdC8ux3m/bnASy3uP6HGTVE3fryVnMmHwP5VYc4tKQ1vFi3v2iuu+TRcBAOBOJN8/6eJ6vNL+Hn1cfBOEiad4a9a+xMDGba+TCBjhWlet6xJj3LwfoIhvY2O7NIgHf62DZNSVhh5ARudo+ZQZ+hnnKC4ntG+oIQ8h9rFXtv1v53ighu6UIXXUspwj5UWolpQ6OviAwrjCs0i0DM=
  file_glob: true
  file: "libbitc*{tar.gz,deb,rpm}"
  skip_cleanup: true
  on:
    repo: libbitc/libbitc
    tags: true
    condition: $DEPLOY = "yes"
